"""add_is_pinned_to_chat_sessions

Revision ID: 4a56794507bd
Revises: fdb2ea07a2ac
Create Date: 2026-04-06 23:36:52.366500

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a56794507bd'
down_revision: Union[str, Sequence[str], None] = 'fdb2ea07a2ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_sessions', sa.Column('is_pinned', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_sessions', 'is_pinned')
    # ### end Alembic commands ###
