"""create_menus_table

Revision ID: 62217bcce3a4
Revises: e15318911333
Create Date: 2026-04-04 00:17:55.068983

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from sqlalchemy.sql import table, column
from datetime import datetime
import uuid


# revision identifiers, used by Alembic.
revision: str = '62217bcce3a4'
down_revision: Union[str, Sequence[str], None] = 'e15318911333'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('menus',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('path', sa.String(), nullable=False),
    sa.Column('icon', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###

    # --- NOSSA MÁGICA: INSERINDO OS DADOS AUTOMATICAMENTE ---
    menu_table = table(
        'menus',
        column('id', sa.UUID(as_uuid=True)),
        column('title', sa.String),
        column('path', sa.String),
        column('icon', sa.String),
        column('role', sa.String),
        column('order_index', sa.Integer),
        column('is_active', sa.Boolean),
        column('created_at', sa.DateTime)
    )

    op.bulk_insert(
        menu_table,
        [
            # === MENUS PÚBLICOS (USER E ADMIN VEEM) ===
            {'id': uuid.uuid4(), 'title': 'Início', 'path': '/dashboard', 'icon': 'home', 'role': 'USER', 'order_index': 1, 'is_active': True, 'created_at': datetime.utcnow()},
            {'id': uuid.uuid4(), 'title': 'Tutor IA', 'path': '/chat', 'icon': 'bot', 'role': 'USER', 'order_index': 2, 'is_active': True, 'created_at': datetime.utcnow()},
            {'id': uuid.uuid4(), 'title': 'Meus Dados', 'path': '/configuracoes', 'icon': 'settings', 'role': 'USER', 'order_index': 3, 'is_active': True, 'created_at': datetime.utcnow()},
            
            # === MENUS ADMINISTRATIVOS (SÓ ADMIN VÊ) ===
            {'id': uuid.uuid4(), 'title': 'Gerenciar Usuários', 'path': '/admin/users', 'icon': 'users_cog', 'role': 'ADMIN', 'order_index': 4, 'is_active': True, 'created_at': datetime.utcnow()},
            {'id': uuid.uuid4(), 'title': 'Novo Usuário', 'path': '/admin/users/new', 'icon': 'user_plus', 'role': 'ADMIN', 'order_index': 5, 'is_active': True, 'created_at': datetime.utcnow()},
            {'id': uuid.uuid4(), 'title': 'Gerenciar Menus', 'path': '/admin/menus', 'icon': 'menu', 'role': 'ADMIN', 'order_index': 6, 'is_active': True, 'created_at': datetime.utcnow()},
        ]
    )
    # --- FIM DA NOSSA MÁGICA ---


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('menus')
    # ### end Alembic commands ###
