"""add_english_level_and_tech_stack_to_users

Revision ID: db3c5490cb92
Revises: 4a56794507bd
Create Date: 2026-04-06 23:49:23.198088

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db3c5490cb92'
down_revision: Union[str, Sequence[str], None] = '4a56794507bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('english_level', sa.String(), nullable=True))
    op.add_column('users', sa.Column('tech_stack', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'tech_stack')
    op.drop_column('users', 'english_level')
    # ### end Alembic commands ###
