"""add_is_pinned_to_chat_messages

Revision ID: fdb2ea07a2ac
Revises: 75bf215460ee
Create Date: 2026-04-06 23:18:15.710323

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fdb2ea07a2ac'
down_revision: Union[str, Sequence[str], None] = '75bf215460ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_messages', sa.Column('is_pinned', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_messages', 'is_pinned')
    # ### end Alembic commands ###
